import re


def parse_eway_bill(data):
    """
    Extract structured fields from an E-Way Bill QR payload.
    """

    result = {
        "eway_bill_number": None,
        "generation_date": None,
        "generation_time": None,
        "generated_by": None
    }

    if not data:
        return result

    # EWB Number
    match = re.search(
        r"EWB\s*No\.?\s*:\s*(\d+)",
        data,
        re.IGNORECASE
    )

    if match:
        result["eway_bill_number"] = match.group(1)

    # Generation Date + Time
    match = re.search(
        r"Gen\.\s*Dt\.?\s*(.*?)(?=Gen\.\s*By|$)",
        data,
        re.IGNORECASE
    )

    if match:
        date_time = match.group(1).strip()

        time_match = re.search(
            r"(\d{1,2}:\d{2}:\d{2}\s*[AP]M)",
            date_time,
            re.IGNORECASE
        )

        if time_match:
            result["generation_time"] = time_match.group(1)

            date_part = date_time[:time_match.start()].strip()

            result["generation_date"] = date_part
        else:
            result["generation_date"] = date_time

    # Generated By
    match = re.search(
        r"Gen\.\s*By\s*(.+)$",
        data,
        re.IGNORECASE
    )

    if match:
        result["generated_by"] = match.group(1).strip()

    return result