import json

try:
    from src.image_loader import load_document
    from src.qr_scanner import scan_qr

    from src.qr.payload_handler import get_payload_info
    from src.qr.result_saver import save_result
    from src.qr.eway_parser import parse_eway_bill
    from src.qr.url_parser import parse_url
    from src.qr.url_browser_extractor import extract_certificate_from_url
    from src.qr.secure_qr_parser import parse_secure_qr

    from src.verification.qr_data_adapter import adapt_qr_data
except ImportError:
    from image_loader import load_document
    from qr_scanner import scan_qr

    from qr.payload_handler import get_payload_info
    from qr.result_saver import save_result
    from qr.eway_parser import parse_eway_bill
    from qr.url_parser import parse_url
    from qr.url_browser_extractor import extract_certificate_from_url
    from qr.secure_qr_parser import parse_secure_qr

    from verification.qr_data_adapter import adapt_qr_data


# =========================================
# DOCUMENT
# =========================================

# Uncomment the path for the document you want to process:
# file_path = "test_Documents\\genuine\\certificate10.png"   # E-Way Bill
# file_path = "test_Documents\\genuine\\certificateHeckathon.jpg"  # URL
# file_path = "test_Documents\\genuine\\certificate4.webp"   # Secure QR
# file_path = "test_Documents\\genuine\\json_certificate_qr.png"  # JSON
# file_path = "test_Documents\\genuine\\Data_Science_Essentials_with_Python_certificate_photo.pdf"
file_path = "test_Documents\\genuine\\WhatsApp Image 2026-09-20 at 8.42.11 PM.jpeg"


# =========================================
# LOAD DOCUMENT
# =========================================

image = load_document(file_path)


# =========================================
# QR SCAN
# =========================================

data, points, method = scan_qr(image)


# =========================================
# PAYLOAD HANDLING
# =========================================

result = get_payload_info(data, method)


# =========================================
# DISPLAY BASIC QR RESULT
# =========================================

print("--------------------------------")

if result["qr_detected"]:

    print("✅ QR Code Detected")

    print()
    print("Detection Method :", result["detection_method"])
    print("QR Type          :", result["qr_type"])
    print("Data Length      :", result["data_length"])

    print()
    print("Decoded Data")
    print("--------------------------------")
    print(result["decoded_data"])

else:
    print("❌ No QR Code Detected")


# =========================================
# QR-SPECIFIC PARSING
# =========================================

# qr_comparable_data is populated by each branch below.
# It is the common-schema dict used for verification.
qr_comparable_data = None


# =====================================
# E-WAY BILL
# =====================================

if result["qr_type"] == "E-Way Bill":

    eway_data = parse_eway_bill(result["decoded_data"])

    result["eway_bill_data"] = eway_data

    qr_comparable_data = adapt_qr_data("E-Way Bill", eway_data)

    result["qr_comparable_data"] = qr_comparable_data

    print()
    print("E-Way Bill Parsed Data")
    print("--------------------------------")
    print("EWB Number      :", eway_data["eway_bill_number"])
    print("Generation Date :", eway_data["generation_date"])
    print("Generation Time :", eway_data["generation_time"])
    print("Generated By    :", eway_data["generated_by"])

    print()
    print("Comparable QR Data")
    print("--------------------------------")
    print(qr_comparable_data)


# =====================================
# URL  →  browser extraction  →  common schema
# =====================================

if result["qr_type"] == "URL":

    # Step 1: parse and validate URL structure
    url_data = parse_url(result["decoded_data"])

    result["url_data"] = url_data

    print()
    print("URL Parsed Data")
    print("--------------------------------")
    print("URL    :", url_data["url"])
    print("Domain :", url_data["domain"])
    print("Path   :", url_data["path"])

    # Step 2: browser extraction (Playwright)
    # Extracts certificate fields from the live page.
    if url_data["url"]:

        extracted = extract_certificate_from_url(url_data["url"])

        result["url_extracted_data"] = extracted

        print()
        print("Browser-Extracted Certificate Data")
        print("--------------------------------")
        print("Name           :", extracted.get("name"))
        print("Certificate ID :", extracted.get("certificate_id"))
        print("Course         :", extracted.get("course"))
        print("Issue Date     :", extracted.get("issue_date"))
        print("Issuer         :", extracted.get("issuer"))

        # Step 3: adapt extracted data to common schema
        qr_comparable_data = adapt_qr_data("URL", extracted)

    else:
        # URL was malformed – adapt the bare url_data
        qr_comparable_data = adapt_qr_data("URL", url_data)

    result["qr_comparable_data"] = qr_comparable_data

    print()
    print("Comparable QR Data")
    print("--------------------------------")
    print(qr_comparable_data)


# =====================================
# JSON
# =====================================

if result["qr_type"] == "JSON":

    try:
        json_data = json.loads(result["decoded_data"])

        result["json_data"] = json_data

        print()
        print("JSON Parsed Data")
        print("--------------------------------")
        print(json_data)

        qr_comparable_data = adapt_qr_data("JSON", json_data)

        result["qr_comparable_data"] = qr_comparable_data

        print()
        print("Comparable QR Data")
        print("--------------------------------")
        print(qr_comparable_data)

    except json.JSONDecodeError:
        print()
        print("❌ Invalid JSON payload")


# =====================================
# GOVERNMENT SECURE QR  (structural only)
# =====================================

if result["qr_type"] == "Government Secure QR":

    secure_data = parse_secure_qr(result["decoded_data"])

    result["secure_qr_data"] = secure_data

    # Encrypted payload is NOT decrypted.
    # adapt_secure_qr returns an empty common record.
    qr_comparable_data = adapt_qr_data(
        "Government Secure QR", secure_data
    )

    result["qr_comparable_data"] = qr_comparable_data

    print()
    print("Secure QR Structural Data")
    print("--------------------------------")
    print("Version               :", secure_data.get("version"))
    print("Identifier            :", secure_data.get("identifier"))
    print("Flag                  :", secure_data.get("flag"))
    print(
        "Base64 Payload Length :",
        len(secure_data.get("secure_payload") or "")
    )
    print("Decoded Byte Length   :", secure_data.get("base64_decoded_length"))
    print("Verification Status   :", secure_data.get("verification_status"))

    print()
    print("Comparable QR Data (no decryption)")
    print("--------------------------------")
    print(qr_comparable_data)





# =========================================
# SAVE RESULT
# =========================================

output_file = save_result(result)

print()
print("✅ Result saved at:")
print(output_file)